meta:
  environment: ~
  boundary_meter:
    org_id_and_api_key: (( merge ))

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: boundary_z1
    templates:
    - name: boundary-meter
      release: boundary
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    update:
      canaries: 10
    properties:
      boundary_meter:
        org_id_and_api_key: (( meta.boundary_meter.org_id_and_api_key ))

networks: (( merge ))

properties: {}
